---
title: "ADMT-25 Meeting Notes"
description: |
  Notes and action items from the 25th Argo Data Management Team meeting held in Trieste, Italy.
author:
  - name: Christopher Gordon
    url: https://github.com/cgrdn
date: 2024-10-30
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Summary of relevant actions from the 25th Argo Data Management Team held in Trieste, Italy during October 21-25, 2024. All actions are linked to a github issue in order to effectively track their progress.

## Day 1

- Nathan Briggs pointed out that MEDS CTS5 floats appear to be jumping to discrete longitudes. It is all floats so likely a bug/rounding error in their processing at the DAC level. WMO numbers: 4902684-4902688. _Action: look into location info on these floats, find source of discrete longitude jumps._ ([#3](https://github.com/ArgoCanada/argo-dm/issues/3))
- Remove inactive, DMQC'ed floats from the greylist (which will soon be renamed). _Action: check for any inactive, already D-moded floats on existing greylist._ ([#4](https://github.com/ArgoCanada/argo-dm/issues/4))

## Day 2

- Dalhousie is buying new floats with RBR Tridente (chlorophyll, backscatter, 3rd channel) and Trios Opus (nitrate) sensors. These sensors are new to the MEDS data system and in different stages of the Argo data system as well. Tridente sensors are in the experimental phase and will need to be placed in the aux directory at the GDAC, not in the main data system. The Opus sensor I am not sure what phase it is in but may also need to go in the aux directory. _Action: (1) verify current sensor phase of the Opus sensor (experimental, pilot, etc) (2) establish processing of Tridente and Opus sensors at MEDS (3) establish new RTQC of Tridente and Opus sensors at MEDS (at least 1+ ADMT away, will await updated manual)._ ([#5](https://github.com/ArgoCanada/argo-dm/issues/5))
- High quality shipboard measurements alongside deployment of floats equipped with Tridente sensors will be helpful for validation and acceptance into the main data system. See Nathan Briggs TTT presentation. _Action: coordinate with Dalhousie to ensure these floats are deployed alongside such measurements, such as on AZMP or AZOMP missions._ ([#6](https://github.com/ArgoCanada/argo-dm/issues/6))

## Day 3

- Some MEDS DOXY_QC=1 still in data system. _Action: check remaining DOXY_QC=1, find source, fix._ ([#7](https://github.com/ArgoCanada/argo-dm/issues/7))
- BBP_ADJUSTED not being filled in RT at MEDS. _Action: fill BBP_ADJUSTED in RT with 1:1 copy of BBP._ ([#8](https://github.com/ArgoCanada/argo-dm/issues/8))
- IRRADIANCE manual being updated. _Action: verify that current processing/flagging of RT irradiance data is correct._ ([#9](https://github.com/ArgoCanada/argo-dm/issues/9))
- Nitrate in oxygen deficient zones - see Josh Plant's presentation. _Action: check on oxygen profiles from floats with Nitrate sensors._ ([#10](https://github.com/ArgoCanada/argo-dm/issues/10))
- Upon implementation of geographically defined CHLA adjustment, must fill SCIENTIFIC_CALIB fields. _Action: await official documentation on implementation, request standard formulation of SCIENTIFIC_CALIB fields for homogeneity in the data system._
- Josh Plant now using WOA23 for oxygen audit over WOA18. _Action: update reference source for bgcArgoDMQC package._ ([#74](https://github.com/ArgoCanada/bgcArgoDMQC/issues/74))
- Josh Plant pointed out some MEDS floats with variable gains. I recognized the WMO numbers as floats that had been adjusted by Henry Bittig. The three of us discussed and Henry explained that this was from a batch of optodes that were batch calibrated with poor temperature characterization. Thus the gains are temperature dependent, but correct. _No action required._

## Day 4

- US to adopt a standard "intermediate" data format/template, as individual programs forward the data onto the AOML DAC. _No action required_ but could be useful to keep an eye on as a common archive format. 
- Should confirm with OceanOps that the WMO numbers in our tracking spreadsheet are the last of Canadian pre-allocated WMO numbers. Once those have been used, request WMO numbers on demand when deployment plans have been formed. If WMO is needed without a deployment plan, can submit a deployment location of (0, 0) to OceanOps. _Action: Chris to confirm with Victor at OceanOps that the list of WMO numbers in tracking spreadsheet are indeed assigned to Argo Canada._
- BODC running coriolis processing chain (not container implementation yet) alongside their core chain. Not unlike the parallel core/BGC systems Anh is operating at MEDS. May be something to consider in moving to a more common infrastructure if/when possible. _No action at this time._
- Some MEDS floats are failing synthetic profile build at coriolis. _Action: check synthetic profile error log for MEDS floats, investigate source of error._  ([#12](https://github.com/ArgoCanada/argo-dm/issues/12))
- Reminder of RBR sqareroot error/correction procedure. _Action: have we implemented this correction?_ ([#13](https://github.com/ArgoCanada/argo-dm/issues/13))

## Day 5

- For NOVA and deep ARVOR floats, should indicate time-of-day (TOD) sampling in config variable in meta file. More widely, Chris and Anh need to review/update meta config variables on a per-float-type basis. _Action: Chris and Anh to review/update config variables in meta file to match float configuration as well as TOD sampling._ ([#14](https://github.com/ArgoCanada/argo-dm/issues/14))
- Ice avoidance information should be stored in netCDF files as well. See John Gilson's presentation. _Action: Ice floats should have ISA info included in netCDF file._ ([#15](https://github.com/ArgoCanada/argo-dm/issues/15))
