on:
  push:
    branches: master

name: Render & Deploy Site

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          install.packages("distill")
        shell: Rscript {0}

      - name: Render Site
        run: |
          rmarkdown::render_site(encoding = "UTF-8")
        shell: Rscript {0}

      - name: Checkout the gh-pages branch
        uses: actions/checkout@master
        with:
          ref: gh-pages
          path: pages-clone

      - name: Deploy source package
        if: success()
        run: |
          cp -rf docs/* pages-clone/
          cd pages-clone
          git add -A
          git commit -m 'Rebuild site' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
